In [1]:
import numpy as np

In [2]:
an_array = np.arange(0,6)
print(an_array)

[0 1 2 3 4 5]


In [3]:
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5]


In [5]:
an_array = np.arange(0,6)
print(np.append(an_array, [6,7,8]))

[0 1 2 3 4 5 6 7 8]


In [7]:
print(np.insert(an_array, 0, [10,11]))

[10 11  0  1  2  3  4  5]


In [8]:
np.delete(an_array, 3)

array([0, 1, 2, 4, 5])

In [9]:
print(an_array * 2)

[ 0  2  4  6  8 10]


In [10]:
print(an_array +5)

[ 5  6  7  8  9 10]


In [11]:
another_array = np.array([2, 5, 7,3, 5, 9, 11])
np.sort(another_array)

array([ 2,  3,  5,  5,  7,  9, 11])

In [12]:
-np.sort(-another_array)

array([11,  9,  7,  5,  5,  3,  2])

In [ ]:
print