In [2]:
import numpy as np

In [3]:
an_array = np.arange(0,11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
first_element = an_array[0]
print(first_element)

0


In [5]:
last_element = an_array[10]
print(last_element)


10


In [8]:
first_five = an_array[0:5]
first_five = an_array[:5]
print(first_five)

[0 1 2 3 4]


In [12]:
last_five = an_array[6:]
print(last_five)

[ 6  7  8  9 10]


In [14]:
first_five_reverse = an_array[4::-1]
print(first_five_reverse)

[4 3 2 1 0]


In [15]:
final_two = an_array[-2:]
print(final_two)

[ 9 10]


In [16]:
print(an_array.size)

11


In [17]:
np.amax(an_array)

10

In [18]:
print(np.amin(an_array))

0


In [19]:
print(np.average(an_array))

5.0
